name: Deploy CRUD app

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  bulid-deploy-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JVM
        usus: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name:  Check
        run: ./mvnw check

          
