name: Deploy CRUD app

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  bulid-deploy-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JVM
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name:  Check
        run: |
          ./mvnw clean install
          ./mvnw test

      - name: Run
        run: |
          ./mvnw spring-boot:run